// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1:string):Promise<string>;

export function DeleteFile(arg1:string,arg2:string):Promise<string>;

export function GetHTMLFiles(arg1:string):Promise<Array<string>>;

export function ReadFileContent(arg1:string,arg2:string):Promise<string>;

export function RenameFileNative(arg1:string,arg2:string):Promise<string>;

export function SaveCode(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectFolder():Promise<string>;

export function SyncFile(arg1:string,arg2:string,arg3:string):Promise<string>;
