// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function GetHTMLFiles(arg1) {
  return window['go']['main']['App']['GetHTMLFiles'](arg1);
}

export function ReadFileContent(arg1, arg2) {
  return window['go']['main']['App']['ReadFileContent'](arg1, arg2);
}

export function SaveCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCode'](arg1, arg2, arg3);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SyncFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncFile'](arg1, arg2, arg3);
}
